interface validateMessage {
    [key: string]: string
}
export const validateMessage: validateMessage = {
    "customer.profile.unauthorized": "Bạn không được ủy quyền để xem hồ sơ này",
    "customer.profile.notfound": "Không tìm thấy hồ sơ khách hàng",
    "customer.profile.update.denied": "Bạn không được phép cập nhật hồ sơ này",
    "customer.profile.update.avatar.null": "Avatar không thể để trống",
    "customer.profile.update.success": "Hồ sơ khách hàng đã được cập nhật thành công",
    "customer.booking.booked.empty": "Bạn chưa có đặt phòng nào",
    "customer.booking.history.empty": "Bạn chưa có lịch sử đặt phòng nào",
    "customer.booking.cancelled.empty": "Bạn chưa có đặt phòng bị hủy nào",
    "customer.booking.notfound": "Không tìm thấy đặt phòng",
    "customer.feedback.unauthorized": "Bạn không được ủy quyền để xem phản hồi này",
    "customer.feedback.empty": "Bạn chưa có phản hồi nào",
    "customer.feedback.notfound": "Không tìm thấy phản hồi",
    "customer.feedback.find.denied": "Bạn không được phép xem phản hồi này",
    "customer.feedback.add.error": "Lỗi khi thêm phản hồi",
    "customer.feedback.add.success": "Phản hồi đã được thêm thành công",
    "customer.booking.edit.error": "Lỗi khi chỉnh sửa đặt phòng",
    "customer.avatar.delete.success": "Avatar đã được xóa thành công",
    "customer.feedback.update.failed": "Cập nhật phản hồi thất bại",
    "manager.household.authorized": "Bạn được ủy quyền để xem hộ gia đình này",
    "manager.household.notfound": "Không tìm thấy hộ gia đình",
    "manager.profile.notfound": "Không tìm thấy hồ sơ quản lý",
    "manager.profile.update.success": "Hồ sơ quản lý đã được cập nhật thành công",
    "manager.profile.update.error": "Lỗi khi cập nhật hồ sơ quản lý",
    "manager.household.booking.notfound": "Hộ gia đình của bạn chưa có đặt phòng nào",
    "manager.household.booking.add.success": "Đặt phòng đã được thêm thành công",
    "manager.household.update.success": "Hộ gia đình đã được cập nhật thành công",
    "manager.household.booking.detail.notfound": "Đặt phòng chưa có chi tiết nào",
    "manager.household.booking.cancel.denied": "Bạn không được phép hủy đặt phòng này",
    "manager.household.booking.cancel.success": "Đặt phòng đã được hủy thành công",
    "manager.booking.notfound": "Không tìm thấy đặt phòng",
    "booking.cancelled.by.manager": "Đặt phòng đã bị hủy bởi quản lý",
    "manager.booking.cancelled.deadline": "Không thể hủy đặt phòng sau 7 ngày kể từ ngày đặt",
    "manager.household.booking.update.success": "Đặt phòng đã được cập nhật thành công",
    "cancellation.history.not.found": "Không tìm thấy lịch sử hủy",
    "manager.room.type.not.found": "Quản lý không có loại phòng này",
    "login.success": "Đăng nhập thành công",
    "login.failed": "Đăng nhập thất bại",
    "login.invalid": "Tên đăng nhập hoặc mật khẩu không hợp lệ",
    "account.email.verify.send.success": "Vui lòng xác nhận email qua liên kết đã được gửi đến địa chỉ email của bạn",
    "account.email.verify.success": "Email đã được xác nhận thành công.",
    "account.email.verify.error": "Xác nhận email thất bại.",
    "account.email.notFound": "Email không tồn tại",
    "account.otp.valid": "Mã OTP hợp lệ",
    "account.otp.notValid": "Mã OTP không hợp lệ",
    "account.otp.hasExpired": "Mã OTP đã hết hạn",
    "account.not.activate": "Tài khoản chưa được kích hoạt.",
    "account.password.notMatch": "Mật khẩu không chính xác.",
    "account.login.failed": "Email hoặc mật khẩu không chính xác.",
    "account.register.success": "Tài khoản đã được đăng ký thành công.",
    "account.reset.password.success": "Mật khẩu đã được đặt lại thành công.",
    "email.confirm.success": "Email đã được xác nhận thành công.",
    "email.exists": "Email đã tồn tại.",
    "email.not.exists": "Email không tồn tại.",
    "email.send.success": "Email đã được gửi thành công.",
    "email.send.error": "Lỗi khi gửi email.",
    "email.otp.send.success": "Mã OTP để thay đổi mật khẩu đã được gửi đến địa chỉ email của bạn.",
    "password.change.success": "Thay đổi mật khẩu thành công.",
    "password.change.error.confirmPassword": "Xác nhận mật khẩu không khớp với mật khẩu mới.",
    "user.not.found": "Người dùng không tồn tại.",
    "user.not.registered": "Người dùng chưa đăng ký.",
    "token.notFound": "Token không tồn tại.",
    "token.hasExpired": "Token đã hết hạn.",
    "internal.server.error": "Lỗi máy chủ nội bộ.",
    "booking.notfound": "Không tìm thấy đặt phòng",
    "booking.denied": "Bạn không được phép xem đặt phòng này",
    "booking.cancelled": "Đặt phòng đã bị hủy",
    "date.invalid": "Ngày nhận phòng hoặc trả phòng không hợp lệ",
    "account.socialLogin.error": "Lỗi khi đăng nhập bằng tài khoản xã hội",
    "required.field": "Trường bắt buộc",
    "avatar.default": "https://storage.googleapis.com/hbs_bucket/avatar-default.jpeg",
    "service.name.exist": "Tên dịch vụ đã tồn tại",
    "service.not.found": "Dịch vụ không tồn tại",
    "service.not.available": "Dịch vụ không khả dụng",
    "service.add.success": "Thêm dịch vụ thành công",
    "service.update.success": "Cập nhật dịch vụ thành công",
    "service.delete.success": "Xóa dịch vụ thành công",
    "service.add.failed": "Thêm dịch vụ thất bại",
    "service.update.failed": "Cập nhật dịch vụ thất bại",
    "service.active.success": "Kích hoạt dịch vụ thành công",
    "service.inactive.failed": "Ngưng hoạt động dịch vụ thất bại",
    "service.not.found.or.user.not.have.permission": "Dịch vụ này không thuộc sở hữu của bạn. Bạn không có quyền thực hiện hành động này",
    "room.not.found": "Phòng không tồn tại",
    "room.add.success": "Thêm phòng thành công",
    "room.add.failed": "Thêm phòng thất bại",
    "dorm.add.success": "Thêm phòng ngủ chung thành công",
    "dorm.add.failed": "Thêm phòng ngủ chung thất bại",
    "room.update.success": "Cập nhật phòng thành công",
    "room.update.failed": "Cập nhật phòng thất bại",
    "room.hide.success": "Ẩn phòng thành công",
    "room.hide.failed": "Ẩn phòng thất bại",
    "room.show.success": "Hiển thị phòng thành công",
    "room.show.failed": "Hiển thị phòng thất bại",
    "room.delete.success": "Xóa phòng thành công",
    "room.delete.failed": "Xóa phòng thất bại",
    "dorm.delete.success": "Xóa phòng ngủ chung thành công",
    "dorm.delete.failed": "Xóa phòng ngủ chung thất bại",
    "room.or.dorm.slot.not.enough": "Không đủ chỗ trong phòng hoặc phòng ngủ chung",
    "room.type.not.found": "Không tìm thấy loại phòng",
    "room.type.add.success": "Thêm loại phòng thành công",
    "room.type.add.failed": "Thêm loại phòng thất bại",
    "room.type.update.success": "Cập nhật loại phòng thành công",
    "room.type.update.failed": "Cập nhật loại phòng thất bại",
    "room.type.delete.success": "Xóa loại phòng thành công",
    "room.type.delete.failed": "Xóa loại phòng thất bại",
    "room.type.do.not.have.room.type.or.no.permission": "Hệ thống không có loại phòng hoặc hộ gia đình đã có tất cả các loại phòng",
    "admin.not.found": "Không tìm thấy quản trị viên",
    "admin.profile.not.found": "Không tìm thấy hồ sơ quản trị viên",
    "admin.profile.update.success": "Cập nhật hồ sơ quản trị viên thành công",
    "admin.profile.avatar.update.success": "Cập nhật avatar quản trị viên thành công",
    "report.export.success": "Xuất báo cáo thành công",
    "report.export.error": "Lỗi khi xuất báo cáo",
    "news.create.success": "Tạo tin tức thành công",
    "news.update.success": "Cập nhật tin tức thành công",
    "news.delete.success": "Xóa tin tức thành công",
    "news.not.found": "Không tìm thấy tin tức",
    "news.create.error": "Lỗi khi tạo tin tức",
    "news.update.error": "Lỗi khi cập nhật tin tức",
    "news.delete.error": "Lỗi khi xóa tin tức",
    "media.create.and.update.success": "Tạo và cập nhật phương tiện thành công",
    "media.delete.error": "Lỗi khi xóa phương tiện",
    "media.create.and.update.error": "Lỗi khi tạo và cập nhật phương tiện",
    "local.product.add.success": "Thêm sản phẩm địa phương thành công",
    "local.product.update.success": "Cập nhật sản phẩm địa phương thành công",
    "local.product.not.found": "Không tìm thấy sản phẩm địa phương",
    "local.product.add.failed": "Thêm sản phẩm địa phương thất bại",
    "local.product.update.failed": "Cập nhật sản phẩm địa phương thất bại",
    "local.product.position.not.found": "Không tìm thấy vị trí sản phẩm địa phương",
    "local.product.position.set.success": "Thiết lập vị trí sản phẩm địa phương thành công",
    "local.product.position.set.failed": "Thiết lập vị trí sản phẩm địa phương thất bại",
    "local.product.position.delete.success": "Xóa vị trí sản phẩm địa phương thành công",
    "local.product.position.delete.failed": "Xóa vị trí sản phẩm địa phương thất bại",
    "local.product.active.success": "Kích hoạt sản phẩm địa phương thành công",
    "local.product.inactive.success": "Ngưng hoạt động sản phẩm địa phương thành công",
    "local.product.delete.success": "Xóa sản phẩm địa phương thành công",
    "customer.break.system": "Hệ thống khách hàng đã bị hỏng",
    "area.not.found": "Không tìm thấy khu vực",
    "area.add.success": "Thêm khu vực thành công",
    "area.update.success": "Cập nhật khu vực thành công",
    "area.delete.success": "Xóa khu vực thành công",
    "area.is.empty": "Khu vực trống",
    "facility.not.found": "Không tìm thấy tiện nghi",
    "facility.add.success": "Thêm tiện nghi thành công",
    "facility.update.success": "Cập nhật tiện nghi thành công",
    "facility.update.failed": "Cập nhật tiện nghi thất bại",
    "facility.delete.success": "Xóa tiện nghi thành công",
    "facility.delete.failed": "Xóa tiện nghi thất bại",
    "no.facility.exits": "Hệ thống không có tiện nghi nào",
    "homestay.not.found": "Không tìm thấy homestay",
    "homestay.add.success": "Thêm homestay thành công",
    "homestay.update.success": "Cập nhật homestay thành công",
    "homestay.update.failed": "Cập nhật homestay thất bại",
    "homestay.delete.success": "Xóa homestay thành công",
    "homestay.delete.failed": "Xóa homestay thất bại",
    "homestay.hide.success": "Ẩn homestay thành công",
    "homestay.show.success": "Hiển thị homestay thành công",
    "homestay.save.failed": "Lưu homestay thất bại",
    "household.not.found": "Không tìm thấy hộ gia đình",
    "household.name.exist": "Tên hộ gia đình đã tồn tại",
    "household.add.success": "Thêm hộ gia đình thành công",
    "household.add.failed": "Thêm hộ gia đình thất bại",
    "household.update.success": "Cập nhật hộ gia đình thành công",
    "household.update.failed": "Cập nhật hộ gia đình thất bại",
    "household.delete.success": "Xóa hộ gia đình thành công",
    "household.delete.failed": "Xóa hộ gia đình thất bại",
    "household.hide.success": "Ẩn hộ gia đình thành công",
    "household.hide.failed": "Ẩn hộ gia đình thất bại",
    "household.show.success": "Hiển thị hộ gia đình thành công",
    "household.show.failed": "Hiển thị hộ gia đình thất bại",
    "household.set.position.success": "Thiết lập vị trí hộ gia đình thành công",
    "household.set.position.failed": "Thiết lập vị trí hộ gia đình thất bại",
    "household.delete.position.success": "Xóa vị trí hộ gia đình thành công",
    "household.delete.position.failed": "Xóa vị trí hộ gia đình thất bại",
    "household.top.exist": "Top đã tồn tại",
    "household.top.is.not.number": "Top không phải là số",
    "household.top.invalid": "Top không nằm trong khoảng từ 1-5",
    "household.is.empty": "Hộ gia đình trống",
    "contact.not.found": "Không tìm thấy liên hệ",
    "contact.add.success": "Thêm liên hệ thành công",
    "contact.update.success": "Cập nhật liên hệ thành công",
    "contact.delete.success": "Xóa liên hệ thành công",
    "FAQ.not.found": "Không tìm thấy câu hỏi thường gặp",
    "FAQ.add.success": "Thêm câu hỏi thường gặp thành công",
    "FAQ.update.success": "Cập nhật câu hỏi thường gặp thành công",
    "FAQ.delete.success": "Xóa câu hỏi thường gặp thành công",
    "FAQ.add.failed": "Thêm câu hỏi thường gặp thất bại",
    "FAQ.update.failed": "Cập nhật câu hỏi thường gặp thất bại",
    "FAQ.delete.failed": "Xóa câu hỏi thường gặp thất bại",
    "village.media.not.found": "Không tìm thấy phương tiện ...",
    "village.media.add.success": "Thêm phương tiện thành công",
    "village.media.update.success": "Cập nhật phương tiện thành công",
    "village.media.update.failed": "Cập nhật phương tiện thất bại",
    "village.media.update.saveall.failed": "Lưu phương tiện thất bại",
    "village.information.update.failed": "Cập nhật thông tin thất bại",
    "image.not.found": "Không tìm thấy hình ảnh",
    "image.empty": "Hình ảnh trống",
    "payment.not.found": "Không tìm thấy thanh toán",
    "feedback.not.found": "Không tìm thấy đánh giá",
    "feedback.add.success": "Thêm đánh giá thành công",
    "feedback.update.success": "Cập nhật đánh giá thành công",
    "feedback.delete.success": "Xóa đánh giá thành công",
    "feedback.update.failed": "Cập nhật đánh giá thất bại",
    "feedback.delete.failed": "Xóa đánh giá thất bại",
    "feedback.hide.success": "Ẩn đánh giá thành công",
    "feedback.hide.failed": "Ẩn đánh giá thất bại",
    "feedback.show.success": "Hiển thị đánh giá thành công",
    "feedback.show.failed": "Hiển thị đánh giá thất bại",
    "no.permission": "Bạn không có quyền thực hiện hành động này",
    "bad.request": "Yêu cầu không hợp lệ",
    "error.format.search": "Lỗi định dạng tìm kiếm",
    "error.format.date": "Lỗi định dạng ngày",
    "booking.not.available": "Đặt phòng không khả dụng",
    "error.booking.date": "Lỗi ngày đặt phòng",
    "booking.not.found": "Không tìm thấy đặt phòng",
    "booking.success": "Đặt phòng thành công",
    "booking.detail.not.found": "Không tìm thấy chi tiết đặt phòng",
    "error.update.booking": "Lỗi cập nhật đặt phòng",
    "booking.update.success": "Cập nhật đặt phòng thành công",
    "booking.cancel.success": "Hủy đặt phòng thành công",
    "booking.denied.cancel": "Bạn không được phép hủy đặt phòng này",
    "booking.room.not.available": "Trong số phòng bạn vừa đặt, đã có phòng được đặt trước đó. Vui lòng chọn lại phòng khác.",
    "booking.manager.not.belong": "Đặt phòng này không thuộc quản lý của bạn",
    "booking.check.in.failed": "Check in thất bại",
    "booking.booked.failed": "Đặt phòng thất bại",
    "booking.do.not.have.blank.room": "Không có phòng trống",
    "booking.blank.room.not.enough": "Không đủ phòng trống",
    "checkin.success": "Check in thành công",
    "checkout.success": "Check out thành công",
    "payment.response.success": "Thanh toán thành công",
    "payment.error": "Lỗi thanh toán",
    "payment.gateway.not.found": "Không tìm thấy cổng thanh toán",
    "payment.success": "Thanh toán thành công",
    "payment.refund.success": "Hoàn tiền thành công",
    "account.not.found": "Không tìm thấy tài khoản",
    "account.update.status.success": "Cập nhật trạng thái tài khoản thành công",
    "account.update.status.error": "Cập nhật trạng thái tài khoản thất bại",
    "account.delete.success": "Xóa tài khoản thành công",
    "account.delete.error": "Xóa tài khoản thất bại",
    "account.not.found.or.permission.denied": "Tài khoản không tồn tại hoặc bạn không có quyền thực hiện hành động này",
    "account.email.exist": "Email đã tồn tại",
    "account.create.success": "Tạo tài khoản thành công",
    "account.permission.denied": "Bạn không có quyền thực hiện hành động này",
    "request.update.status.error": "Cập nhật trạng thái yêu cầu thất bại",
    "request.update.status.success": "Cập nhật trạng thái yêu cầu thành công",
    "request.not.found": "Không tìm thấy yêu cầu",
    "request.delete.success": "Xóa yêu cầu thành công",
    "request.delete.error": "Xóa yêu cầu thất bại",
    "request.send.success": "Gửi yêu cầu thành công",
    "noti.send.success": "Gửi thông báo thành công",
    "household.room.type.not.found": "Household không có loại phòng này",
    "household.room.type.add.success": "Thêm loại phòng thành công",
    "household.room.type.add.failed": "Thêm loại phòng thất bại",
    "household.room.type.update.success": "Cập nhật loại phòng thành công",
    "household.room.type.update.failed": "Cập nhật loại phòng thất bại",
    "household.room.type.delete.success": "Xóa loại phòng thành công",
    "household.room.type.delete.failed": "Xóa loại phòng thất bại",
    "household.room.type.do.not.have.room.type.or.no.permission": "Hệ thống không có loại phòng hoặc hộ gia đình đã có tất cả các loại phòng",
    "household.room.type.convert.failed": "Chuyển đổi loại phòng thất bại",
    "household.do.not.have.homestay": "Household không có homestay",
    "account.social.login.cannot.login":"Bạn đang sử dụng tài khoản xã hội để đăng nhập. Bạn không thể đăng nhập.",
    "account.social.login.can.not.change.or.forget.password":"Bạn đang sử dụng tài khoản xã hội để đăng nhập. Bạn không thể thay đổi hoặc quên mật khẩu.",
}   